name: jellyfinmediaplayer
base: core22
version: '1.9.1'
summary: Jellyfin Desktop Client based on Plex Media Player
description: |
  Desktop client using jellyfin-web with embedded MPV player. Media plays within the same window using the jellyfin-web interface unlike Jellyfin Desktop. Supports audio passthrough. Based on Plex Media Player.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64

apps:
  jellyfinmediaplayer:
    command-chain: [snap/command-chain/alsa-launch]
    command: usr/bin/jellyfinmediaplayer
    desktop: usr/share/applications/com.github.iwalton3.jellyfin-media-player.desktop
    extensions: [ gnome ]
    environment:
      ALWAYS_USE_PULSEAUDIO: 1
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - screen-inhibit-control
      - network
      - shmem
      - alsa
      
plugs:
  shmem:
    interface: shared-memory
    private: true

environment:
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}
  QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP/lib/$CRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP_DESKTOP_RUNTIME/lib/$CRAFT_ARCH_TRIPLET${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}
  LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  QTWEBENGINEPROCESS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/libexec/QtWebEngineProcess
  DISABLE_WAYLAND: 1

layout:
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5
  /usr/share/jellyfinmediaplayer:
    bind: $SNAP/usr/share/jellyfinmediaplayer
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  jellyfinmediaplayer:
    after: [alsa-mixin, desktop-glib-only]
    plugin: dump
    source: https://github.com/jellyfin/jellyfin-media-player/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/jellyfin-media-player_${SNAPCRAFT_PROJECT_VERSION}-1_amd64-jammy.deb
    source-type: deb
    stage-packages:
      - libmpv1
      - libqt5webengine5
      - libcec6
      - qml-module-qtwebengine
      - qml-module-qtwebchannel
      - qml-module-qtquick-controls
      - libqt5x11extras5
      - libqt5xml5
      - libqt5webenginecore5
      - libglu1-mesa
      - libblas3
      - liblapack3
      - libcuda1-384
      - libgtk-3-0
    override-build: |
      craftctl default
      sed -i 's|Icon=com.github.iwalton3.jellyfin-media-player|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.iwalton3.jellyfin-media-player.svg|' ${CRAFT_PART_INSTALL}/usr/share/applications/com.github.iwalton3.jellyfin-media-player.desktop
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
